spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.16.60:3306/wechat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: Landray@2026
    hikari:
      pool-name: HikariCP-DEV
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 30000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  mail:
    host: smtp.smart.org.cn
    port: 465
    username: auth-noreply@smart.org.cn
    password: i03GxjizwrIQPm4a
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
    default-encoding: UTF-8

dingtalk:
  client-id: dingkvganesqfe5rlm7r
  client-secret: G4dapskIrUi6-UABXuzqNtiIMdNPt_qxvFIJ9KnpfDSSx_E1HGA2HMh_guTAYYCI
  agentId: 4312159084
  duration: 3600

wechat:
  appid: wxb87f5e064b721821
  secret: 074d1a95eacb895069eb8648005135f7
  template-id: nVH8QWImfvGfdgdSHr9iPuM9f4A7xpwAOSWiLutlBTg
  url: https://api.weixin.qq.com
  grant_type: authorization_code
  client_grant_type: client_credential
  duration: 3600

sys-notify:
  api-url: http://10.1.17.35:8080/api/sys-notify/sysNotifyTodoRestService/getTodo
  basic-auth-token: cmVzdC1ub3RpZnk6eWt5MTIz
  dingding-detail-url: https://portal.smart.org.cn/api/smart-dingding/smartDingdingDetailRestService/dingdingDetail

thread-pool:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 100
  keep-alive-seconds: 60
  thread-name-prefix: dingtalk-event-

logging:
  level:
    com.example: debug
    org.springframework: info

captcha:
  email:
    from: auth-noreply@smart.org.cn
    subject: 【系统通知】绑定验证码
